apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
patchesJson6902:
  - target:
      group: core
      version: v1
      kind: ConfigMap
      name: config
    path: config-patch.yaml
