// Load the config generated by scalajs-bundler
var config = require('./scalajs.webpack.config');

var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = config;

module.exports.plugins = [
    new HtmlWebpackPlugin()
];

module.exports.devServer = {
    ...module.exports.devServer,
    historyApiFallback: true
}

module.exports.output = {
    ...module.exports.output,
    publicPath: '/'
}
