apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: lightbend-console
      name: api
    path: api-node-port.yaml
