apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: lightbend-console-api
    app.kubernetes.io/part-of: lightbend-console
